### ISSUE TITLE
Backspace not working well with characters for createTextMask

### ISSUE THREAD

**Issue by ninjarails** [renato-bohler/redux-form-input-masks#27]
### What are you reporting?

* [x] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

'+1 (999) 999-9999 x99999' - I can't remove x with backspace.
### What is the expected behavior?

Should able to remove x with backspace.
### What's your environment?

Mac Os high sierra 10.13.3

**Comment by renato-bohler** [comment]
What is the pattern for the mask you've created?

If the pattern is `'+1 (999) 999-9999 x99999'`, you really shoudn't be able to delete the `x` character, because those chars on the pattern that aren't defined in maskDefinitions are mask characters (such as parenthesis, space and dash on this example).

A sandbox would be greatly appreciated.

**Comment by renato-bohler** [comment]
Oh, I think I get it now. The caret position should isn't being correctly controlled on this situation.

![issue 2](https://user-images.githubusercontent.com/25781956/38179401-4855e356-35f9-11e8-9fff-14325d55b3a8.gif)

**Comment by ninjarails** [comment]
Thanks for your quick response. It's exactly what I faced today. So I can't remove `x` and the number before `x` by backspace. It's not good UX, I think.

**Comment by renato-bohler** [comment]
Closed by #31
