### ISSUE TITLE
Numeric mask characters and mask behavior 

### ISSUE THREAD

**Issue by TimMeade** [renato-bohler/redux-form-input-masks#49]
### What are you reporting?

* [ ] Bug
* [x] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

When masking a number a underscore (_) is used in place of expected number.   

Secondary request,  if non numeric numbers are present i.e. phone number (___) ___-_____  all non numeric characters are present at all time.   

### What is the expected behavior?
We would like the mask character to be defined.   Sometimes you may want pound sign (#),  we actually prefer space ( ).  

Secondary wish:   Have the mask build as input filled out.   See pictures for examples with phone numbers.

Just enhancements better user experience.

### Other information

![screenshot 2018-07-14 07 30 03](https://user-images.githubusercontent.com/1386476/42724121-716552da-873a-11e8-8527-f0f471abaeab.png)
![screenshot 2018-07-14 07 49 51](https://user-images.githubusercontent.com/1386476/42724127-81aead62-873a-11e8-9bb0-481e94d66fe8.png)
![screenshot 2018-07-14 07 48 41](https://user-images.githubusercontent.com/1386476/42724130-855c2d5e-873a-11e8-9eae-5518bdf9e7d8.png)
![screenshot 2018-07-14 07 48 49](https://user-images.githubusercontent.com/1386476/42724132-883aac6c-873a-11e8-8170-cbd6920a0fa3.png)

**Comment by TimMeade** [comment]
OK i found placeholder so that fixes the underscore issue.  

Leaving this open as i still think the fill behavior is important.

**Comment by sjarvie** [comment]
In this case, are you looking for a numeric placeholder?

E.g.
```
 (000) 000-0000
```
I am looking to do the same thing.

**Comment by renato-bohler** [comment]
@TimMeade You can change the placeholder with the `placeholder` option, as you already discovered. You can also change the fill behaviour by setting the `guide` option (when `true` the guide will be filled with placeholders, when `false` it will be masked as the user fills the field). Does that meet your requirements?

**Comment by renato-bohler** [comment]
@sjarvie You actually can use `0` as a placeholder for a numeric input. The only thing to keep in mind is that the `placeholder` cannot be matched by any of the `maskDefinitions`, so if you use `0` as a placeholder, it will not be possible to input zeroes on your field.

The mask below should work fine:

```jsx
const phoneMask = createTextMask({
  pattern: '(###) ###-####',
  placeholder: '0',
  maskDefinitions: {
    '#': {
      regExp: /[1-9]/
    },
  },
});
```

**Comment by sjarvie** [comment]
I see.

What we are looking to do is use 0 as a placeholder in a phone number entry field, so we would need 0 as an input in the field. Would it possible to add an additional flag `maskPlaceholder` to the mask definition as boolean which decides whether if the placeholder should be matched by the mask?

Happy to brainstorm with you further.

**Comment by renato-bohler** [comment]
The only problem I see in allowing the placeholder to be matched by the mask definition is that it would be hard to implement/control wether the character was actually inputted or is only a placeholder.

Think of `(010) 000-0000`, for example. Has the second zero been filled or is it a placeholder? It's not possible to determine with only this information (and that is pretty much all we have in our scenario). When I focus this field, how would we decide where to put the caret? It should go to the last unfilled position so that is easy for the user to continue to fill the field, but the same problem occurs: we can't know for sure what the user have actually inputted.

I agree this is a limitation, and this is not good, but I'm not sure if solving this would be even possible (at least without making the code a complete mess).

If you think otherwise I would also be happy to know your ideas :smile:

**Comment by renato-bohler** [comment]
I'm closing this, as it is related to #53.
