### ISSUE TITLE
react-final-form compatibility

### ISSUE THREAD

**Issue by taschetto** [renato-bohler/redux-form-input-masks#65]
### What are you reporting?

* [ ] Bug
* [X] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?

This library is the GO-TO solution when you want to easily format inputs when using redux-form. It's amazing, easy to use, flexible and with a great API. Sadly, redux-form is being left aside from its creator for a new library (https://github.com/final-form/final-form / https://github.com/final-form/react-final-form) which is great and have a lot of benefits over redux-form. Unfortunately, redux-form-input-masks doesn't work with final-form. It would be amazing to use it along final-form.

### What is the expected behavior?

Create masks to use with final-form in the same manner we are used to do using redux-form.

Thank you very much and congratulations on the great work in this library.

**Comment by renato-bohler** [comment]
Hi @taschetto. As soon as I saw `final-form`, back in March 2018, I immediately tried to port `redux-form-input-masks`. I even registered the `npm` package `final-form-input-masks`.

Unfortunately, on `final-form`, the `parse` function has no access to the last value of the input, and we really need it on `redux-form-input-masks`.

I've added an issue there (https://github.com/final-form/react-final-form/issues/192) but since then I've had no response other than a workaround that's not enough for our needs.

If you know of anyone that can help with this issue, I would gladly implement `final-form-input-masks`. But, until then, there's not much that I can do :disappointed:

**Comment by taschetto** [comment]
Hi @renato-bohler. Thank you for your quick reply. That is sad. I'll see what I can do to help. For now I'll stick with `redux-form` and `redux-form-input-masks` that works amazingly with my app.

**Comment by renato-bohler** [comment]
All right, I'll keep watching the issue on `final-form`.

I'll close this for now. If `final-form` resolve their side, I'll reopen it and implement the adapter ASAP.

**Comment by taschetto** [comment]
@renato-bohler I was digging this issue and reading react-final-form source code. `final-form` is, by design, independent of state. This and the fact that we do not have a native way to get the last value of an input (only the original value) makes me think that it would be impossible to get the last value of the input in this scenario.

Do you think it might be possible to `final-form-input-masks` doesn't depend on `previousValue`?

**Comment by taschetto** [comment]
Hey, @renato-bohler. How are you solving this problem these days? Are you still using redux-form?

**Comment by renato-bohler** [comment]
Hey @taschetto... sorry for the really late reply. I'm being very busy these last months :sweat: 

I'm currently not using `final-form` on the projects I work on, I'm still on `redux-form`.

My plan, in the next weeks (or months...), is to test and merge all those dependabot's pull requests first, then trying some of the issues that I think are feasible without having to rewrite everything from scratch.

After that, I'm thinking on trying to solve this issue. I would have to check the code to see if it's possible to make those input masks without using previous values... but that may require some seriours rewriting.

If I decide to rewrite this library to make it compatible with `final-form`, I'll design the new version with all open issues in mind, because some of them would need some rewriting anyway.

But given how things are going, this may take some time, unfortunately.
