### ISSUE TITLE
Placeholder appears for guide:false in createTextMask

### ISSUE THREAD

**Issue by varunthefalcon** [renato-bohler/redux-form-input-masks#69]
### What are you reporting?

* [x] Bug
* [ ] Feature request
* [ ] Code refactor
* [ ] Continuous Integration (CI) improvement
* [ ] Changes in documentation (docs)
* [ ] Other (describe)

### What is the current behavior?
  The prop guide: false should remove the pattern place holder in the field when no input is present. But wierd place holder ' ( ' appears for this pattern: '(999) 999-9999'. Changing the pattern to '[999] 999-9999' gives desired empty place holder.
 
 

### What is the expected behavior?
 The prop guide: false should completely remove any pattern place holder in the field when no input is present.

### Sandbox Link
https://codesandbox.io/s/749586m240

### What's your environment?
redux-form-input-masks : 2.0.1
ReactJS : 16.6.3
NodeJS : 10.15.0
NPM      : 6.4.1
Browser : Chrome 72.0.3626.121 (64-bit)
OS : Ubuntu 18.04

**Comment by renato-bohler** [comment]
Hello!

So, when the `guide` is set to `false`, the value will be displayed only to the last informed character. In this case, if input is empty and there's some characters before any inputtable char in the pattern, these leading characters will be shown. That is the expected behaviour. For example:

```js
createTextMask({ pattern: '(999)', guide: false }); // will format to `(` if the value is empty
createTextMask({ pattern: '[999]', guide: false }); // will format to `[` if the value is empty
```

If you want that in this case nothing is shown, you can set the `allowEmpty` option to true:

```js
createTextMask({ pattern: '(999)', guide: false, allowEmpty: true }); // will format to `` if the value is empty
createTextMask({ pattern: '[999]', guide: false, allowEmpty: true }); // will format to `` if the value is empty
```

Also, I couldn't reproduce this behaviour by forking your codesandbox ([here](https://codesandbox.io/s/mjop1lwvrj)), using the our latest version (`2.0.1`). For instance, these masks:

```js
const phoneMaskParenthesis = createTextMask({
  pattern: "(999) 999-9999",
  guide: false,
  allowEmpty: true
});

const phoneMaskBrackets = createTextMask({
  pattern: "[999] 999-9999",
  guide: false,
  allowEmpty: true
});
```

Behave like this (which, again, is the expected behaviour):

![Peek 2019-03-20 19-16](https://user-images.githubusercontent.com/25781956/54723054-0fb72c00-4b45-11e9-95e0-3288037c0e07.gif)

**Comment by varunthefalcon** [comment]
Thank you for your response.
